version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/rain0416/Around
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t estherlai/around .
          docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
          docker push estherlai/around
